apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayuntamiento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ayuntamiento
  template:
    metadata:
      labels:
        app: ayuntamiento
    spec:
      containers:
        - name: ayuntamiento
          image: pgomezbo/ayuntamiento:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: ayuntamiento-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-server:8888
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/ayuntamiento
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://auth-server:9000/auth/realms/proyecto-final
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: http://auth-server:9000/auth/realms/proyecto-final/protocol/openid-connect/certs
