apiVersion: v1
kind: ConfigMap
metadata:
  name: bicicletas-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
  SERVICE_BICICLETASDATA_URL: "http://bicicletas-data:8088"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://auth-server:9000/auth/realms/proyecto-final"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://auth-server:9000/auth/realms/proyecto-final/protocol/openid-connect/certs"
