apiVersion: apps/v1
kind: Deployment
metadata:
  name: polucion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polucion
  template:
    metadata:
      labels:
        app: polucion
    spec:
      containers:
        - name: polucion
          image: pgomezbo/polucion:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: polucion-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-server:8888
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/polucion
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: polucion-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: polucion-secret
                  key: MYSQL_PASSWORD
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/polucion
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://auth-server:9000/auth/realms/proyecto-final
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: http://auth-server:9000/auth/realms/proyecto-final/protocol/openid-connect/certs