apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayuntamiento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ayuntamiento
  template:
    metadata:
      labels:
        app: ayuntamiento
    spec:
      containers:
        - name: ayuntamiento
          image: pgomezbo/ayuntamiento:v1.3
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: ayuntamiento-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: ayuntamiento-config
                  key: SPRING_CONFIG_IMPORT
            - name: SERVICE_AYUNTAMIENTODATA_URL
              valueFrom:
                configMapKeyRef:
                  name: ayuntamiento-config
                  key: SERVICE_AYUNTAMIENTODATA_URL
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: ayuntamiento-config
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              valueFrom:
                configMapKeyRef:
                  name: ayuntamiento-config
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
